CREATE TABLE group_members (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   expense_group_id BIGINT NOT NULL,
   display_name VARCHAR(100) NOT NULL,
   email VARCHAR(320) NOT NULL,
   version BIGINT NOT NULL DEFAULT 0,
   created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
   updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

   CONSTRAINT fk_group_members_expense_group
       FOREIGN KEY (expense_group_id)
           REFERENCES expense_groups(id)
           ON DELETE CASCADE,

   CONSTRAINT uk_group_members_group_email
       UNIQUE (expense_group_id, email)
);